config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users

  resources :discussions, only: %i[index show new create edit update destroy] do
    resources :posts, only: %i[create show edit update destroy], module: :discussions

    collection do
      get "category/:id", to: "categories/discussions#index", as: :category
    end
  end
  root to: "discussions#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :category, counter_cache: true, touch: true
  validates :name, presence: true

  delegate :name, prefix: true, to: :category, allow_nil: true

  has_many :posts, dependent: :destroy

  accepts_nested_attributes_for :posts

  scope :pinned_first, -> { order(pinned: :desc, updated_at: :desc) }

  broadcasts_to :category, inserts_by: :prepend

  after_create_commit -> { broadcast_prepend_to %w[discussions discussion] }
  after_update_commit -> { broadcast_replace_to %w[discussions discussion] }
  after_destroy_commit -> { broadcast_remove_to %w[discussions discussion] }

  def to_param
    "#{id}-#{name.downcase.truncate(100, separator: " ")}".parameterize
  end
end

app/controllers/categories/discussions_controller.rb
module Categories
  class DiscussionsController <  ApplicationController
    before_action :authenticate_user!
    before_action :set_category
    def index
      @discussions = @category.discussions.pinned_first
      render "discussions/index"
    end

    private
    def set_category
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, only: %i[show edit update destroy]
    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @discussion }
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def edit
      # code here
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def show
      # code here
    end

    def destroy
      @post.destroy!
      respond_to do |format|
        format.html { redirect_to @discussion }
      end
    end

    private
    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: %i[edit show update destroy]

  def index
    @discussions = Discussion.all.pinned_first
  end

  def show
    @posts = @discussion.posts.order(created_at: :asc)
    @new_post = @discussion.posts.new
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "Discussion was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        @discussion.broadcast_replace(partial: "discussions/header", locals: { discussion: @discussion })

        if @discussion.saved_change_to_category_id?
          old_category_id, new_category_id = @discussion.saved_change_to_category_id

          old_category = Category.find(old_category_id)
          new_category = Category.find(new_category_id)

          @discussion.broadcast_remove_to old_category
          @discussion.broadcast_prepend_to new_category

          old_category.reload.broadcast_replace_to "categories"
          new_category.reload.broadcast_replace_to "categories"
        end

        if @discussion.saved_change_to_closed?
          @discussion.broadcast_action_to(
            @discussion,
            action: :replace,
            target: "new_post_form",
            partial: "discussions/posts/form",
            locals: { post: @discussion.posts.new }
          )
        end

        format.html { redirect_to @discussion, notice: "Discussion was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @discussion.destroy!
      redirect_to discussions_path, alert: "Discussion was successfully destroyed."
    end
  end

  private
  def discussion_params
    params.require(:discussion).permit(:name, :category_id, :closed, :pinned, posts_attributes: :body)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
end

app/views/discussions/_discussion.html.erb
<li id="<%= dom_id(discussion) %>" class="list-row items-center">
  <%= link_to discussion.name, discussion, class: "text-lg" %>
  <span>Pinned: <%= discussion.pinned %> | Closed:  <%= discussion.closed %></span>
  <span>Category: <%= discussion.category_name %> | Posts: <%= discussion.posts_count %></span>
  <div>
    <%= link_to "Edit", edit_discussion_path(discussion), class: "btn btn-primary btn-sm" %>
    <%= link_to "Delete", discussion, data: { turbo_method: :delete, confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
  </div>
</li>

app/views/discussions/_form.html.erb
<%= form_with model: discussion do |f| %>
  <% if discussion.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(discussion.errors.count, "error") %> prevented this discussion from being saved</h2>
      <ul>
        <% discussion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3 flex flex-col gap-2">
    <%= f.label :name, class: "label" %>
    <%= f.text_field :name, class: "input", placeholder: "How do I...?" %>
  </div>

  <div class="mb-3 flex flex-col gap-2">
    <%= f.label :category, class: "label" %>
    <%= f.collection_select :category_id, Category.sorted, :id, :name,
      { include_blank: "Pick a category" }, { class: "select"} %>
  </div>

  <div class="mb-3 flex gap-2">
    <%= f.label :pinned, class: "label" %>
    <%= f.checkbox :pinned, class: "checkbox" %>
  </div>

  <div class="mb-3 flex gap-2">
    <%= f.label :closed, class: "label" %>
    <%= f.checkbox :closed, class: "checkbox" %>
  </div>

  <% if discussion.new_record? %>
    <%= f.fields_for :posts do |p| %>
      <div class="mb-3">
        <%= p.label :body, "Start discussion" %>
        <%= p.rich_text_area :body, placeholder: "Kickoff the discussion", class: "textarea" %>
      </div>
    <% end %>
  <% end %>

  <div class="mb-3">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/discussions/_header.html.erb
<%= turbo_frame_tag dom_id(discussion), class: "w-full" do %>
  <div class="flex items-center justify-between w-full">
    <div>
      <h1 class="text-xl"><%= discussion.name %></h1>
      <span class="fs-6">
        <% if discussion.pinned %>
          <span class="badge badge-primary">Pinned</span>
        <% end %>

        <% if discussion.closed %>
          <span class="badge badge-primary">Closed</span>
        <% end %>
      </span>
    </div>
    <div>
      <%= link_to "Edit", edit_discussion_path(discussion), class: "btn btn-primary btn-sm" %>
      <%= link_to "Delete", discussion, data: { turbo_method: :delete, confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
    </div>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Edit Discussion</h1>
<%= turbo_frame_tag dom_id(@discussion), class: "w-full card items-center" do %>
  <%= render "form", discussion: @discussion %>
  <%= link_to "Cancel", @discussion, class: "btn" %>
<% end %>

app/views/discussions/index.html.erb
<% if @category.present? %>
  <%= turbo_stream_from @category %>
<% else %>
  <%= turbo_stream_from "discussions" %>
<% end %>
<section class="discussions w-full">
  <div class="flex mb-2 justify-between items-center w-full">
    <h1 class="font-bold text-4xl">Discussions</h1>
    <%= link_to "New Discussions", new_discussion_path, class: "btn btn-neutral" %>
  </div>
  <%= turbo_stream_from "categories" %>
  <div class="flex w-full gap-2">
    <div class="w-1/5 categories">
      <h5 class="text-lg mb-2">Categories</h5>
      <%= render partial: "categories/category", collection: Category.sorted %>
    </div>
    <div class="w-4/5">
      <% if @category %>
        <h4 class="text-xl">Viewing discussions in <%= @category.name %></h4>
      <% end %>
      <ul id="discussions" class="list gap-4">
        <% if @discussions.any? %>
          <%= render partial: "discussions/discussion", collection: @discussions %>
        <% else %>
          No discussions yet
        <% end %>
      </ul>
    </div>
  </div>
</section>

app/views/discussions/new.html.erb
<h1>New Discussion</h1>

<%= render "form", discussion: @discussion %>

app/views/discussions/show.html.erb
<%= turbo_stream_from @discussion %>
<%= render "header", discussion: @discussion %>

<div id="posts" class="p-4 w-full h-[75vh] overflow-y-scroll">
  <%= render partial: "discussions/posts/post", collection: @posts %>
</div>

<div id="<%= dom_id @new_post %>" class="w-full">
  <%= render "discussions/posts/form", post: @new_post %>
</div>