config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users

  resources :discussions, only: %i[index show new create edit update destroy] do
    resources :posts, only: %i[create show edit update destroy], module: :discussions

    collection do
      get "category/:id", to: "categories/discussions#index", as: :category
    end
  end
  root to: "discussions#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :category, counter_cache: true, touch: true
  validates :name, presence: true

  delegate :name, prefix: true, to: :category, allow_nil: true

  has_many :posts, dependent: :destroy

  accepts_nested_attributes_for :posts

  scope :pinned_first, -> { order(pinned: :desc, updated_at: :desc) }

  broadcasts_to :category, inserts_by: :prepend

  after_create_commit -> { broadcast_prepend_to %w[discussions discussion] }
  after_update_commit -> { broadcast_replace_to %w[discussions discussion] }
  after_destroy_commit -> { broadcast_remove_to %w[discussions discussion] }

  def to_param
    "#{id}-#{name.downcase.truncate(100, separator: " ")}".parameterize
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion, counter_cache: true, touch: true
  belongs_to :user, default: -> { Current.user }
  has_rich_text :body

  after_create_commit -> { broadcast_append_to discussion, partial: "discussions/posts/post", locals: { post: self } }
  after_update_commit -> { broadcast_replace_to discussion, partial: "discussions/posts/post", locals: { post: self } }
  after_destroy_commit -> { broadcast_remove_to discussion }
  validates :body, presence: true
end

app/controllers/categories/discussions_controller.rb
module Categories
  class DiscussionsController <  ApplicationController
    before_action :authenticate_user!
    before_action :set_category
    def index
      @discussions = @category.discussions.pinned_first
      render "discussions/index"
    end

    private
    def set_category
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, only: %i[show edit update destroy]
    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @discussion }
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def edit
      # code here
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def show
      # code here
    end

    def destroy
      @post.destroy!
      respond_to do |format|
        format.html { redirect_to @discussion }
      end
    end

    private
    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: %i[edit show update destroy]

  def index
    @discussions = Discussion.all.pinned_first
  end

  def show
    @posts = @discussion.posts.order(created_at: :asc)
    @new_post = @discussion.posts.new
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "Discussion was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        @discussion.broadcast_replace(partial: "discussions/header", locals: { discussion: @discussion })

        if @discussion.saved_change_to_category_id?
          old_category_id, new_category_id = @discussion.saved_change_to_category_id

          old_category = Category.find(old_category_id)
          new_category = Category.find(new_category_id)

          @discussion.broadcast_remove_to old_category
          @discussion.broadcast_prepend_to new_category

          old_category.reload.broadcast_replace_to "categories"
          new_category.reload.broadcast_replace_to "categories"
        end

        if @discussion.saved_change_to_closed?
          @discussion.broadcast_action_to(
            @discussion,
            action: :replace,
            target: "new_post_form",
            partial: "discussions/posts/form",
            locals: { post: @discussion.posts.new }
          )
        end

        format.html { redirect_to @discussion, notice: "Discussion was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @discussion.destroy!
      redirect_to discussions_path, alert: "Discussion was successfully destroyed."
    end
  end

  private
  def discussion_params
    params.require(:discussion).permit(:name, :category_id, :closed, :pinned, posts_attributes: :body)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
end

app/views/discussions/posts/_form.html.erb
<%= turbo_frame_tag "#{dom_id(post)}_form", target: "_top", class: "w-full" do %>
  <% if post.discussion.closed? && post.new_record? %>
    <div class="alert alert-warning alert-outline" role="alert">This discussion is currently locked.</div>
  <% else %>
    <%= form_with model: [post.discussion, post] do |f| %>
      <% if post.errors.any? %>
        <div class="alert alert-error">
          <h2>
            <%= pluralize(post.errors.count, 'error') %>
            prohibited this post from being saved:
          </h2>
          <ul>
            <% post.errors.each do |error| %>
              <li>
                <%= error.full_message %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="flex w-full gap-2">
        <div class="flex-1">
          <%= f.label :body, class: "label hidden" %>
          <%= f.text_field :body, class: "input w-full", placeholder: "Add a comment", autofocus: true %>
        </div>
        <%= f.submit "Send", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/discussions/posts/_header.html.erb
<div class="chat-header"><%= post.user.username %></div>
<div class="chat-footer">Posted on: <%= post.created_at %></div>

app/views/discussions/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
  <div class="chat <%= post.user == Current.user ? 'chat-end' : 'chat-start' %>">
    <%= render "discussions/posts/header", post: %>

    <div class="chat-bubble">
      <%= link_to post.body, edit_discussion_post_path(post.discussion, post), class:"tooltip", "data-tip": "Edit" %>
    </div>
  </div>
<% end %>

app/views/discussions/posts/create.turbo_stream.erb
<%= turbo_stream.replace "new_post_form" do %>
  <%= render partial: "discussions/posts/form", formats: :html, locals: { post: @post } %>
<% end %>

app/views/discussions/posts/edit.html.erb
<%= turbo_frame_tag dom_id @post do %>
  <div class="chat <%= @post.user == Current.user ? 'chat-end' : 'chat-start' %>">
    <%= render "discussions/posts/header", post: @post %>
    <div class="chat-bubble">
      <%= form_with model: [@post.discussion, @post] do |f| %>
        <%= f.label :body, class: "hidden" %>
        <%= f.text_field :body, value: @post.body.body.to_plain_text, autofocus: true, class: "input-ghost" %>
      <% end %>
      <%= link_to "Cancel", discussion_path(@post.discussion) %>
      <%= link_to "Delete", discussion_post_path(@post.discussion, @post) , data: { turbo_method: :delete } %>
    </div>
  </div>
<% end %>