config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users

  resources :discussions, only: %i[index show new create edit update destroy] do
    resources :posts, only: %i[create show edit update destroy], module: :discussions

    collection do
      get "category/:id", to: "categories/discussions#index", as: :category
    end
  end
  root to: "discussions#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info m-4">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning m-4">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<div class="navbar bg-base-100 shadow-sm">
  <div class="flex-1">
    <%= link_to "Hotwire Forums", root_path, class: "btn btn-ghost text-xl" %>
    <%= link_to "Discussions", discussions_path, class: "btn btn-ghost" %>
    <%= link_to "Categories", categories_path, class: "btn btn-ghost" %>
  </div>
  <div class="flex-none">
    <div class="dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
        . . .
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
        <% if user_signed_in? %>
          <li><%= link_to Current.user.username, edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }%></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>