config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users

  resources :discussions, only: %i[index show new create edit update destroy] do
    resources :posts, only: %i[create show edit update destroy], module: :discussions

    collection do
      get "category/:id", to: "categories/discussions#index", as: :category
    end
  end
  root to: "discussions#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :discussions, dependent: :nullify

  after_create_commit -> { broadcast_prepend_to "categories" }
  after_update_commit -> { broadcast_replace_to "categories" }
  after_destroy_commit -> { broadcast_remove_to "categories" }

  scope :sorted, -> { order(name: :asc) }

  def to_param
    "#{id}-#{name.downcase.to_s[0...100]}".parameterize
  end
end

app/controllers/categories/discussions_controller.rb
module Categories
  class DiscussionsController <  ApplicationController
    before_action :authenticate_user!
    before_action :set_category
    def index
      @discussions = @category.discussions.pinned_first
      render "discussions/index"
    end

    private
    def set_category
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name, :discussions_count ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="flex items-center w-full justify-between">
  <div class="justify-between w-full flex items-center">
    <strong class="block font-medium mb-1"><%= link_to category.name, category_discussions_path(category) %></strong>
    <strong class="badge badge-neutral"> <%= category.discussions_count %></strong>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul class="list-disc ml-6">
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": category.errors[:name].none?, "border-red-400 focus:outline-red-600": category.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :discussions_count %>
    <%= form.number_field :discussions_count, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": category.errors[:discussions_count].none?, "border-red-400 focus:outline-red-600": category.errors[:discussions_count].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<% content_for :title, "Categories" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categories</h1>
    <%= link_to "New category", new_category_path, class: "btn btn-neutral" %>
  </div>

  <div id="categories" class="list flex gap-2">
    <%= turbo_stream_from "categories" %>
    <% if @categories.any? %>
      <%= render @categories %>
    <% else %>
      <p class="text-center my-10">No categories found.</p>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<% content_for :title, "Showing category" %>

<div class="md:w-2/3 w-full">

  <h1 class="font-bold text-4xl">Showing category</h1>

  <%= render @category %>

  <%= link_to "Edit this category", edit_category_path(@category), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this category", @category, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>